name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set env
        run: echo "GITHUB_BRANCH=$(echo $GITHUB_REF_NAME-$GITHUB_SHA)" >> $GITHUB_ENV  
 
      - name: Build Docker image
        run: |
          docker buildx create --use
          docker buildx inspect default --bootstrap
          docker buildx build --file Dockerfile -t wjt40398/my-app-image:$GITHUB_REF_NAME-$GITHUB_SHA --load .

      - name: Push Docker image to Docker Hub
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username wjt40398 --password-stdin
          docker push wjt40398/my-app-image:$GITHUB_REF_NAME-$GITHUB_SHA
                    
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3.0.0  
        with:
          token: ${{ secrets.PAT }}
          repository: wtp43/Intrend-lab
          event-type: app-update
          client-payload: |-
            {
              "ref": $GITHUB_REF_NAME,
              "docker_image": wjt40398/my-app-image:$GITHUB_REF_NAME-$GITHUB_SHA
            }
